# GRE 协议配置示例
interface:
  name: "eth0"
  promiscuous: true
  buffer_size: 65535

forwarder:
  protocol: "gre"
  destination: "192.168.1.100"
  port: "9066"
  max_packet_size: 65535
  queue_size: 1000

log_level: "info"
